export const routeurls = Object.freeze({
    BASE_API_URL: 'http://localhost:5000',
    MAIN_COMPANY_URL: "/maincompany",
    ROLES_URL: "/roles",
    USERS_URL: "/users",
    CUSTOMER_URL: "/customer",
    LOGIN_URL: "/login",
    EMPLOYEE_URL: "/employee",
    SALESORDERS_URL: "/salesorders",
    PRODUCT_CATEGORY_URL: "/productcategory",
    PRODUCT_SUB_CATEGORY_URL: "/productsubcategory",
    SALES_ORDER_DETAILS_URL: "/salesorderdetails",
    PAYMENT_SALES_URL: "/paymentsales",
    PURCHASE_CATEGORY_URL: "/purchasecategory",
    PURCHASE_SUB_CATEGORY_URL: "/purchasesubcategory",
    SUPPLIER_URL: "/supplier",
    PURCHASE_ORDERS_URL: "/purchaseorder",
    PURCHASE_ORDER_DETAILS_URL: "/purchaseorderdetail",
    SALARY_PAYROLL_URL: "/salarypayroll",
    OFFICE_PURCHASE_ITEM_LIST_URL: "/officepurchaseitemlist",
    OFFICE_EXPENDITURE_URL: "/officeexpenditure",
    ASSET_URL: "/assets",
    PRODUCT_STOCK_URL: "/productstock",
  });
  